package views;
/**
 *
 * @author Azael_Mendoza
 */
public class ViewBurbujaDescendente extends javax.swing.JPanel {

    /**
     * Creates new form ViewBurbujaDescendente
     */
    public ViewBurbujaDescendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_users_input = new javax.swing.JLabel();
        jlb_resultado = new javax.swing.JLabel();
        jtf_users_input = new javax.swing.JTextField();
        jbtn_insertar = new javax.swing.JButton();
        jbtn_ascendente = new javax.swing.JButton();
        jbtn_descendente = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_promedio = new javax.swing.JButton();
        jsp_lista_numeros = new javax.swing.JScrollPane();
        jli_lista_numeros = new javax.swing.JList();

        setBackground(new java.awt.Color(51, 51, 51));

        jlb_users_input.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_users_input.setForeground(new java.awt.Color(204, 204, 204));
        jlb_users_input.setText("Input:");

        jlb_resultado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_resultado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_resultado.setText("...");

        jtf_users_input.setBackground(new java.awt.Color(51, 51, 51));
        jtf_users_input.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_users_input.setForeground(new java.awt.Color(204, 204, 204));

        jbtn_insertar.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_insertar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_insertar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_insertar.setText("Insertar");

        jbtn_ascendente.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_ascendente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_ascendente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ascendente.setText("Ascendente");

        jbtn_descendente.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_descendente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_descendente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_descendente.setText("Descendente");

        jbtn_eliminar.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");

        jbtn_promedio.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_promedio.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_promedio.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_promedio.setText("Promedio");

        jli_lista_numeros.setBackground(new java.awt.Color(51, 51, 51));
        jli_lista_numeros.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jli_lista_numeros.setForeground(new java.awt.Color(204, 204, 204));
        jsp_lista_numeros.setViewportView(jli_lista_numeros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_users_input)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_users_input, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsp_lista_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_descendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtn_promedio, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jbtn_ascendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_users_input)
                    .addComponent(jtf_users_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_insertar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jsp_lista_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ascendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_descendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_promedio)))
                .addGap(18, 18, 18)
                .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_ascendente;
    public javax.swing.JButton jbtn_descendente;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_insertar;
    public javax.swing.JButton jbtn_promedio;
    public javax.swing.JLabel jlb_resultado;
    public javax.swing.JLabel jlb_users_input;
    public javax.swing.JList jli_lista_numeros;
    public javax.swing.JScrollPane jsp_lista_numeros;
    public javax.swing.JTextField jtf_users_input;
    // End of variables declaration//GEN-END:variables
}
